#!/usr/bin/env zsh
echo "Hello $USERNAME !"

# get the shell
is_zsh=false
is_bash=false

if [ -n "${ZSH_VERSION:-}" ]; then
   is_zsh=true
elif [ -n "${BASH_VERSION:-}" ]; then
   is_bash=true
else
   echo "SHell type not found, quitting"
   return 1
fi


#http://stackoverflow.com/questions/9901210/bash-source0-equivalent-in-zsh
if $is_zsh ; then
  DOTFILES_ROOT="$(cd "$(dirname "${(%):-%N}")" ; pwd -P)"
elif $is_bash ; then
  DOTFILES_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P)"
fi


echo Loading dotfiles from "$DOTFILES_ROOT"

search_dotfiles(){
  find -H "$DOTFILES_ROOT" -name "*.$1" -not -path '*.git'
}


# Load zsh files
search_dotfiles sh | while read f ; do . $f ; done

if $is_zsh ; then
  search_dotfiles zsh | while read f; do . $f ; done
elif $is_bash ; then
  search_dotfiles bash | while read f; do . $f ; done
fi


# symlink files
search_dotfiles symlink | while read file; do
	ln -sf "$file" "$HOME/.$(basename "$file" .symlink)"
done


# Cleaning
unset is_zsh is_bash
unset -f search_dotfiles


if [ -f "$HOME/profile" -a -z "${NOT_LOAD_PROFILE:-}" ] ;then
  source "$HOME/profile"
fi




