#!/usr/bin/env bash

echo "Hello $USERNAME !"

#http://stackoverflow.com/questions/9901210/bash-source0-equivalent-in-zsh
DOTFILES_ROOT="$(cd "$(dirname "${(%):-%N}")" ; pwd -P)"

echo Loading dotfiles from "$DOTFILES_ROOT"


# Load zsh files
find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.zsh' -not -path '*.git' |\
while read file; do
	# protect ourselves against not working files
	if zsh -eu "$file" ; then
		source $file
	else
		echo "source [$file] didn't worked"
	fi
done


# Should link the symlink files, maybe only once per day ?








