#!/usr/bin/env dash
# dash is the simpliest sh we can find
set -eu

cd "`dirname "$0"`"


# exec with zsh as file and source
echo "ZSH - file"
zsh -eu bootstrap > /dev/null
echo "ZSH - source"
zsh -eu -c 'source bootstrap' >/dev/null

echo "BASH - file"
bash -eu bootstrap >/dev/null
echo "BASH - source"
bash -eu -c 'source bootstrap' >/dev/null


echo "All test passed well"
